<a href="https://colab.research.google.com/github/25061127-cmd/data-science-toolkit/blob/main/tutorial_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
arr_2x2 = np.array([[1, 2], [3, 4]])
print("2x2：\n", arr_2x2)

2x2：
 [[1 2]
 [3 4]]


In [8]:
random_arr_3x4 = np.random.rand(3, 4)
print("3x4：\n", random_arr_3x4)

3x4：
 [[0.06350244 0.48781954 0.69160121 0.42905291]
 [0.29008771 0.73369131 0.01992873 0.0684497 ]
 [0.09817393 0.16865477 0.70211809 0.68543087]]


In [9]:
ones_arr = np.ones((3, 3))
zeros_arr = np.zeros((3, 3))
print("Array of ones：\n", ones_arr)
print("Array of zeros：\n", zeros_arr)

Array of ones：
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array of zeros：
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
random_arr_6x3 = np.random.rand(6, 3)
transposed_arr = random_arr_6x3.T
print("Original 6x3 random array:\n", random_arr_6x3)
print("Transposed array:\n", transposed_arr)

Original 6x3 random array:
 [[0.71815076 0.74374319 0.54845743]
 [0.59986894 0.51803784 0.1325829 ]
 [0.0636237  0.95453617 0.51044178]
 [0.46829564 0.64404312 0.35348902]
 [0.73329087 0.98639128 0.76787547]
 [0.31320816 0.30034497 0.47086677]]
Transposed array:
 [[0.71815076 0.59986894 0.0636237  0.46829564 0.73329087 0.31320816]
 [0.74374319 0.51803784 0.95453617 0.64404312 0.98639128 0.30034497]
 [0.54845743 0.1325829  0.51044178 0.35348902 0.76787547 0.47086677]]


In [11]:
n, p, m = 2, 3, 4
arr1 = np.random.rand(n, p)
arr2 = np.random.rand(p, m)
dot_product = np.dot(arr1, arr2)
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Dot product result:\n", dot_product)

Array 1:
 [[0.01140072 0.53432972 0.48206793]
 [0.72586192 0.19631808 0.57622674]]
Array 2:
 [[0.50005342 0.73571215 0.75204766 0.9974047 ]
 [0.20551117 0.14124477 0.65541941 0.68118595]
 [0.45263602 0.71706119 0.93406986 0.91413442]]
Dot product result:
 [[0.333713   0.42953113 0.80906908 0.81602392]
 [0.66413627 0.97494416 1.21278946 1.38445589]]
